### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'int'.

### ISSUE THREAD

**Issue by Hatsushira** [Esri/arcgis-python-api#1489]
Using the arcgis module version arcgis-2.1.0.3-py3.9 and all dependencies. Numpy was installed not seperately but from arcgis dependency.

**To Reproduce**
```python
spatial_dataframe.spatial.to_featurelayer('aktive-faelle-geoloc-covid-19', folder='COVID')
```
error:
> Traceback (most recent call last):
>   File "path to my script.py", line 85, in <module>
>     create_anzahl_faelle()
>   File "path to my script.py", line 55, in create_anzahl_faelle
>     new_sp.spatial.to_featurelayer('aktive-faelle-geoloc-covid-19', folder='COVID')
>   File "D:\Python\lib\site-packages\arcgis\features\geo\_accessor.py", line 2846, in to_featurelayer
>     result = content.import_data(
>   File "D:\Python\lib\site-packages\arcgis\gis\__init__.py", line 7569, in import_data
>     ds = df.spatial.to_featureclass(
>   File "D:\Python\lib\site-packages\arcgis\features\geo\_accessor.py", line 2637, in to_featureclass
>     result = to_featureclass(
>   File "D:\Python\lib\site-packages\arcgis\features\geo\_io\fileops.py", line 1108, in to_featureclass
>     res = _pyshp2(df=df, out_path=out_location, out_name=fc_name)
>   File "D:\Python\lib\site-packages\arcgis\features\geo\_io\fileops.py", line 1300, in _pyshp2
>     elif isinstance(df[c].loc[idx], (np.int, np.int32)):
>   File "D:\Python\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
>     raise AttributeError(__former_attrs__[attr])
> AttributeError: module 'numpy' has no attribute 'int'.
> `np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
> The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
>     https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
> Exception ignored in: <function Writer.__del__ at 0x0000028E1E960CA0>
> Traceback (most recent call last):
>   File "D:\Python\lib\site-packages\shapefile.py", line 1846, in __del__
>     self.close()
>   File "D:\Python\lib\site-packages\shapefile.py", line 1873, in close
>     self.__dbfHeader()
>   File "D:\Python\lib\site-packages\shapefile.py", line 2072, in __dbfHeader
>     raise ShapefileException("Shapefile dbf file must contain at least one field.")
> shapefile.ShapefileException: Shapefile dbf file must contain at least one field.

**Expected behavior**
No error message. Did work with version 2.0.1

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser none
 - Python API Version 2.1.0.3

**Comment by r7butler** [comment]
I came here to report this same bug since i was having this same exact problem yesterday and this morning

This is the spatially enabled dataframe as a pickle
[df.spatial.to_featurelayer_bug.gz](https://github.com/Esri/arcgis-python-api/files/10943622/df.spatial.to_featurelayer_bug.gz)

- OS: MacOS 13.1
- Python API version 2.1.0.3
- numpy version 1.24.1
- pandas version 1.4.1

Based on the error message given by the original poster, specifically this part:

> AttributeError: module 'numpy' has no attribute 'int'.
np.int was a deprecated alias for the builtin int. To avoid this error in existing code, use int by itself. Doing this will not modify any behavior and is safe. 

And the below screenshot:

<img width="866" alt="Screenshot 2023-03-10 at 7 54 13 AM" src="https://user-images.githubusercontent.com/40872002/224362260-1803c660-10c0-46e2-9232-91f036407efb.png">

It looks like going into that file called fileops.py and replacing "np.int" with "int" on line 1300 will fix the problem

As a matter of fact, i went into that file and made that change on my local computer, and then i got a different error, which was "np has no attribute 'float'"

so i went to line 1302 and replaced np.float with float, and then i was able to call the method successfully

**Comment by nanaeaubry** [comment]
Ok thank you for bringing this up, we will make the changes on our end, sorry for this

**Comment by egorbn** [comment]
I've also noticed this in the past, and then did some searching. The np.* aliases have been deprecated by Numpy and need to be changed:

https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated
