### ISSUE TITLE
profile incompatible with keyring 23.0.1 

### ISSUE THREAD

**Issue by slootsky** [Esri/arcgis-python-api#1070]
**Describe the bug**
if keyring 23.0.1 is used, an AttributeError is thrown while creating an arcgis.GIS profile

**To Reproduce**
```python
import sys
# Do this later because it is slow to load.  #import arcgis
import argparse

parser=argparse.ArgumentParser(description="Defines an ArcGIS portal profile to be used with python and arcgis"
	, epilog="Reference: https://developers.arcgis.com/python/guide/working-with-different-authentication-schemes/#Storing-your-credentials-locally")
parser.add_argument("profilename", help="Name of the profile to create")
parser.add_argument("portalurl", help="URL of the Portal to connect to")
parser.add_argument("username", help="Username to connect as")
parser.add_argument("password", nargs='?', help="Password for Username")
parser.add_argument("--certfile", help="Name of Certificate file to use")
args=parser.parse_args()

gis_profile=args.profilename
gis_url=args.portalurl
gis_username=args.username

gis_password=None
if args.password:
	gis_password=args.password
else:
	import getpass
	gis_password=getpass.getpass()

print("Creating profile {}".format(gis_profile))
print("  Connecting to {}".format(gis_url))
print("    as {}".format(gis_username))
print("")

import arcgis
gis = arcgis.GIS(profile=gis_profile, url=gis_url, username=gis_username, password=gis_password, verify_cert=args.certfile)```
error:
```python
Keyring backend being used (keyring.backends.Windows.WinVaultKeyring (priority: 5)) either failed to install or is not recommended by the keyring project (i.e. it is not secure). This means you can not use stored passwords through GIS's persistent profiles. Note that extra system-wide steps must be taken on a Linux machine to use the python keyring module securely. Read more about this at the keyring API doc (http://bit.ly/2EWDP7B) and the ArcGIS API for Python doc (http://bit.ly/2CK2wG8).
Traceback (most recent call last):
  File "create_profile.py", line 31, in <module>
    gis = arcgis.GIS(profile=gis_profile, url=gis_url, username=gis_username, password=gis_password, verify_cert=args.certfile)
  File "C:\Users\jslootsk\AppData\Roaming\Python\Python37\site-packages\arcgis\gis\__init__.py", line 340, in __init__
    profile
  File "C:\Users\jslootsk\AppData\Roaming\Python\Python37\site-packages\arcgis\gis\_impl\_profile.py", line 473, in _retrieve
    password = self._securely_get_password(profile)
  File "C:\Users\jslootsk\AppData\Roaming\Python\Python37\site-packages\arcgis\gis\_impl\_profile.py", line 107, in _securely_get_password
    if self._current_keyring_is_recommended():
  File "C:\Users\jslootsk\AppData\Roaming\Python\Python37\site-packages\arcgis\gis\_impl\_profile.py", line 156, in _current_keyring_is_recommended
    keyring.backends.OS_X.Keyring,
AttributeError: module 'keyring.backends' has no attribute 'OS_X'```
**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser n/a
 - Python API Version 1.9.0

**Additional context**
works with keyring v 19.0.2 doesn't work with keyring v 23.0.1.  I haven't checked the versions in between.

**Comment by achapkowski** [comment]
I cannot reproduce this issue.  Can you please provide some more information on your operating system?  You state you are using Windows 10, but it's pulling OS X backend, so is the system windows or Mac?

**Comment by CMPeng** [comment]
@slootsky You can downgrade the version to be greater than 19 but less than or equal to 21.8.0, or you can install the future released version of our API (1.9.1) in which the version requirement is updated.
