### ISSUE TITLE
arcgis.gis.server.admin.administration.Server Mangles arcgis.gis._impl._con._connection.Connection

### ISSUE THREAD

**Issue by bixb0012** [Esri/arcgis-python-api#748]
The following is describing a change between ArcGIS API for Python 1.6.0 and 1.8.2 (also tested on 1.8.1) that breaks ArcGIS Admin API connections to stand-alone ArcGIS Server sites.  As of yet, I have not been able to find a workaround, so i am rolling back all our production machines to the ArcGIS API for Python 1.6.x branch.

Taking the following code:
```python
from arcgis.gis.server import Server

url = r"https://fqdn/arcgis/admin"
username = # username
password = # password

svr = Server(url, username=username, password=password)
```
In the 1.6.x branch, the connection looks like the following:
```python
>>> svr
<Server at https://fqdn/arcgis/admin>
>>> svr._con.is_logged_in
True
>>> svr._con.baseurl
'https://fqdn/arcgis/admin'
>>>
```
while in the 1.8.x branch the connection looks like:
```python
>>> svr
<Server at https://fqdn/arcgis/admin>
>>> svr._con.is_logged_in
True
>>> svr._con.baseurl
'https://fqdn/arcgis/admin/sharing/rest/'
>>>
```
As you can see, the `baseurl` for the 1.8.x is a non-existent URL.  The bogus `baseurl` is a symptom of a connection that appears to be completely botched because trying to retrieve any of the properties (`machines`, `services`, etc...) from the ArcGIS generate errors:
```python
>>> svr.machines
Traceback (most recent call last):
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\gis\server\_common\_base.py", line 81, in __getattr__
    return self._properties.__getitem__(name)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\_impl\common\_mixins.py", line 340, in __getitem__
    return self._mapping[key]
KeyError: 'machines'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\gis\server\_common\_base.py", line 86, in __getattr__
    raise AttributeError("'%s' object has no attribute '%s'" % (type(self).__name__, name))
AttributeError: 'Server' object has no attribute 'machines'
>>>
```

**Comment by bixb0012** [comment]
I just confirmed the break was introduced in 1.8.0.  I tested 1.7.1 and everything still works, but when I upgrade to 1.8.0 the code breaks.

**Comment by achapkowski** [comment]
@bixb0012 is this a standalone or federated server?

**Comment by achapkowski** [comment]
Also please note that the `Server` class is not to be created by a user per the documentation: https://developers.arcgis.com/python/api-reference/arcgis.gis.server.html#server

**Comment by achapkowski** [comment]
We have a target fix for this for ```1.8.3```.

**Comment by bixb0012** [comment]
@achapkowski, thanks for looking into this issue and getting a fix put into place.  Your prompt attention is great appreciated.

Back to your questions, this is stand-alone Server.  Regarding the comment about Server class should not be created by a user, I assume you mean that applies to federated Server since the 2nd example in the documentation shows creating Server directly by  a user to stand-alone Server.

**Comment by bixb0012** [comment]
@achapkowski , a quick question for you on this topic.  I am currently testing ArcGIS Pro 2.7 beta 3, and it shows ArcGIS API for Python 1.8.3.  I tested this code/issue again, and it still fails.  Is a fix still on track for 1.8.3?  Thanks.
