### ISSUE TITLE
Error to create arcgis.features.FeatureSet.from_dataframe(df) - 'DataFrame' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by flicj-aur** [Esri/arcgis-python-api#1189]
**Describe the bug**
Creating featureset from dataframe error while previously working fine in v1.8.5 currently giving an `AttributeError: 'DataFrame' object has no attribute 'dtype'` in v1.9.1

**To Reproduce**
- query existing feature layer 
- then pandas df merge to get updated fields (after dropping the previous columns)
- then create featureset
``` 
feat_set_update = hostLayer_toUpdate.query(where=filter)
update_df = feat_set_update.sdf
update_df = update_df.merge(in_df,how='left',left_on='p_number',right_on='PROP_NUM')
featureset2 = arcgis.features.FeatureSet.from_dataframe(update_df)
```
error:
```python
In  [2]:
Line 8:     featureset2 = arcgis.features.FeatureSet.from_dataframe(test[i:j])

File C:\..\lib\site-packages\arcgis\features\feature.py, in from_dataframe:
Line 940:   fs = FeatureSet.from_dict(df.spatial.__feature_set__)

File C:\..lib\site-packages\arcgis\features\geo\_accessor.py, in __feature_set__:
Line 2861:  date_cols = [col for col in df.columns if df[col].dtype == "datetime64[ns]"]

File C:\..\site-packages\arcgis\features\geo\_accessor.py, in <listcomp>:
Line 2861:  date_cols = [col for col in df.columns if df[col].dtype == "datetime64[ns]"]

File C:\..\lib\site-packages\pandas\core\generic.py, in __getattr__:
Line 5465:  return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'dtype'
```

**Expected behavior**
Creates the featureset no problem so we can update featurelayer.

**Platform (please complete the following information):**
 - OS using ArcGIS Pro 2.9.1, python code in notebook, signed in to enterprise
 - Browser
 - Python API Version 1.9.1

**Comment by flicj-aur** [comment]
The issue may have been around the merge of dataframes and it creating dataframes so that it couldn't check dtype as that is an attribute of a series.
